services:
    dms.filter_loader:
        class: DMS\Filter\Filters\Loader\FilterLoader
        calls:
         - [ setContainer,  [@service_container] ]

    dms.filter:
        class: DMS\Bundle\FilterBundle\Service\Filter
        arguments:
            filter_loader: @dms.filter_loader

    dms.filter.type_extension:
        class: DMS\Bundle\FilterBundle\Form\Type\FormTypeFilterExtension
        arguments:
            filter: @dms.filter
            auto_filter: %dms_filter.auto_filter_forms%
        tags:
            - { name: form.type_extension, alias: form }
